version: 2

defaults: &defaults
  docker:
    - image: kausal/public-build:7fd7918
  working_directory: /go/src/github.com/kausalco/public

workflows:
  version: 2
  default:
    jobs:
    - lint
    - build-promtail

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint

  build-promtail:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make -C promtail
      - deploy:
          name: Push images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push kausal/promtail:$(git rev-parse --short HEAD)
