groups:
    - name: azure
      rules:
        - alert: AzureVMHighCpuUtilization
          annotations:
            dashboard_url: /a/grafana-csp-app/azure/dashboards/vm
            description: The VM {{ $labels.resourceName }} is under heavy load and may become unresponsive.
            summary: VM CPU utilization is too high.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_compute_virtualmachines_percentage_cpu_average_percent{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"})  > 85
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure Virtual Machines
            serviceId: microsoft.compute/virtualmachines
            severity: critical
        - alert: AzureVMUnavailable
          annotations:
            dashboard_url: /a/grafana-csp-app/azure/dashboards/vm
            description: The VM {{ $labels.resourceName }} is not functioning or crashed, which may require immediate action.
            summary: VM unavailable.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_compute_virtualmachines_vmavailabilitymetric_average_count{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}) != 1
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure Virtual Machines
            serviceId: microsoft.compute/virtualmachines
            severity: critical
        - alert: AzureDatabaseHighDtuConsumption
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Check active queries and optimize indexes or consider scaling up DTUs to handle load in {{ $labels.resourceName }} database.
            summary: High database DTU consumption.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_sql_servers_databases_dtu_consumption_percent_average_percent{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}) > 90
          for: 10m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            severity: critical
        - alert: AzureDatabaseHighStorageUsage
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Archive or delete old data, or scale up storage capacity in {{ $labels.resourceName }} database.
            summary: High database Storage usage.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_sql_servers_databases_storage_percent_maximum_percent{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}) > 95
          for: 15m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: critical
        - alert: AzureDatabaseHighDeadlockCount
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Check {{ $labels.resourceName }} database logs for deadlock details and optimize affected queries.
            summary: High database Deadlock count.
          expr: |
            sum by (job,resourceGroup,subscriptionName,resourceName) (rate(azure_microsoft_sql_servers_databases_deadlock_total_count{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}[5m])) > 5
          for: 10m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: info
        - alert: AzureDatabaseHighUserCpuUsage
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Identify high CPU queries on {{ $labels.resourceName }} database and optimize them.
            summary: High database User CPU usage.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_sql_servers_databases_cpu_percent_average_percent{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}) > 90
          for: 10m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: warning
        - alert: AzureDatabaseHighSystemFailedConnections
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Check network problems, firewall restrictions or high resource consumption affecting application access to the {{ $labels.resourceName }} database.
            summary: High number of database System Failed connections.
          expr: |
            sum by (job,resourceGroup,subscriptionName,resourceName) (rate(azure_microsoft_sql_servers_databases_connection_failed_total_count{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}[5m])) > 10
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: warning
        - alert: AzureDatabaseHighUserFailedConnections
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Check for authentication problems, network configuration errors, firewall issues, or resource constraints, affecting database accessibility for users on database {{ $labels.resourceName }}.
            summary: High number of database User Failed connections.
          expr: |
            sum by (job,resourceGroup,subscriptionName,resourceName) (rate(azure_microsoft_sql_servers_databases_connection_failed_user_error_total_count{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}[5m])) > 10
          for: 15m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: warning
        - alert: AzureDatabaseHighWorkerUsage
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Look for long execution queries, review the number of concurrent queries and requests being sent to the database or check if there are any blocking sessions or deadlocks into the {{ $labels.resourceName }} database.
            summary: High database worker usage.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_sql_servers_databases_workers_percent_average_percent{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}) > 60
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: critical
        - alert: AzureDatabaseHighDataIoUsage
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Review queries with high read or write activity, check if there are missing indexes or inefficient indexes that result in full table scans and assess the volume of transactions into the {{ $labels.resourceName }} database.
            summary: High database data IO usage.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_sql_servers_databases_physical_data_read_percent_average_percent{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}) > 90
          for: 15m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: info
        - alert: AzureDatabaseLowTempdbLogSpace
          annotations:
            dashboard_uid: 82c5b6cf30db5b601c5cc3f5d8d4284d
            description: Look for active sessions that might be using TempDB intensively, identify stored procedures or queries that create temporary tables or objects, and also look for long-running or memory-intensive queries that rely heavily on TempDB into the {{ $labels.resourceName }} database.
            summary: Low database tempdb log space.
          expr: |
            avg by (job,resourceGroup,subscriptionName,resourceName) (azure_microsoft_sql_servers_databases_tempdb_log_used_percent_average_percent{job=~".+",resourceGroup=~".+",subscriptionName=~".+",resourceName=~".+"}) > 60
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-azure
            service: Azure SQL database
            serviceId: microsoft.sql/servers/databases
            severity: critical
    - name: gcp
      rules:
        - alert: GcpCEHighCpuUtilization
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/compute-engine
            description: The VM {{ $labels.instance_name }} is under heavy load and may become unresponsive.
            summary: VM CPU utilization is too high.
          expr: |
            100 * avg by (job,project_id,instance_name) (stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job=~".+",project_id=~".+",instance_name=~".+"}) > 85
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Compute Engine
            serviceId: compute
            severity: critical
        - alert: GcpCEHighIOLatency
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/compute-engine
            description: Check {{ $labels.instance_id }} VM for I/O bottlenecks and upgrade to SSD if necessary.
            summary: VM IO latency is too high.
          expr: |
            avg by (job,project_id,instance_id)(stackdriver_gce_instance_compute_googleapis_com_instance_disk_average_io_latency{job=~".+",project_id=~".+",instance_id=~".+"}) > 5000
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Compute Engine
            serviceId: compute
            severity: critical
        - alert: GcpCloudSQLHighCpu
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/cloud-sql
            description: Check {{ $labels.database_id }} database for high CPU queries and optimize them, or scale up the instance if sustained high usage.
            summary: Database CPU utilization is too high.
          expr: |
            100 * avg by (job,project_id,instance,database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{job=~".+",project_id=~".+",instance=~".+", database_id=~".+"}) > 90
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Cloud SQL
            serviceId: cloudsql
            severity: critical
        - alert: GcpCloudSQLMemoryUsage
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/cloud-sql
            description: Review high-memory queries or add more memory to the {{ $labels.database_id }} instance.
            summary: Database memory utilization is too high.
          expr: |
            100 * avg by (job,project_id,instance,database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_utilization{job=~".+",project_id=~".+",instance=~".+", database_id=~".+"}) > 85
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Cloud SQL
            serviceId: cloudsql
            severity: critical
        - alert: GcpCloudSQLDiskUsage
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/cloud-sql
            description: Delete or archive unused data, or increase disk size to the {{ $labels.database_id }} database.
            summary: Database disk utilization is too high.
          expr: |
            100 * avg by (job,project_id,instance,database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_utilization{job=~".+",project_id=~".+",instance=~".+", database_id=~".+"}) > 85
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Cloud SQL
            serviceId: cloudsql
            severity: critical
        - alert: GcpCloudSQLActiveConnections
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/cloud-sql
            description: Investigate connection pooling settings and connection management in your {{ $labels.database_id }} application database.
            summary: Too many database active connections.
          expr: |
            avg by (job,project_id,instance, database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_mysql_threads{thread_kind="THREADS_CONNECTED", job=~".+",project_id=~".+",instance=~".+", database_id=~".+"}) > 0.9 * avg by (job,project_id,instance, database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_mysql_max_connections{job=~".+",project_id=~".+",instance=~".+", database_id=~".+"})
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Cloud SQL
            serviceId: cloudsql
            severity: critical
        - alert: GcpCloudSQLAbortedConnections
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/cloud-sql
            description: Verify credentials and network settings; check for firewall rules blocking connections for the {{ $labels.database_id }} database.
            summary: More than 5 MySQL failed connections in 5 minutes.
          expr: |
            sum by(job, instance, project_id, database_id)(rate(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_mysql_aborted_connects_count[5m])) > 5
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Cloud SQL
            serviceId: cloudsql
            severity: critical
        - alert: GcpCloudSQLLagSecondsBehindMaster
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/cloud-sql
            description: Check {{ $labels.database_id }} database for network latency between primary and replica; adjust configurations to optimize replication.
            summary: More than 5 seconds lag between database read replica and primary.
          expr: |
            avg by (job,project_id,instance, database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_mysql_replication_seconds_behind_master) > 5
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Cloud SQL
            serviceId: cloudsql
            severity: warning
        - alert: GcpPubSubNumUndeliveredMessages
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/pub-sub
            description: Scale up subscribers or adjust message processing capacity for the {{ $labels.instance }} instance.
            summary: More than 1000 unacknowledged messages for a PubSub subscription.
          expr: |
            avg by (job,project_id,instance)(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_num_undelivered_messages{job=~".+",project_id=~".+",instance=~".+"}) > 1000
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Pub/Sub
            serviceId: pubsub
            severity: warning
        - alert: GcpPubSubUnackedMessageAge
          annotations:
            dashboard_url: /a/grafana-csp-app/gcp/dashboards/pub-sub
            description: Investigate {{ $labels.instance }} instance and speed up message processing; ensure consumers can handle the load.
            summary: Unacknowledged messages for more than 60 seconds for a PubSub subscription.
          expr: |
            avg by (job,project_id,instance)(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_oldest_unacked_message_age{job=~".+",project_id=~".+",instance=~".+"}) > 60
          for: 5m
          keep_firing_for: 10m
          labels:
            namespace: cloud-provider-gcp
            service: Pub/Sub
            serviceId: pubsub
            severity: warning
